kmpkg_check_linkage(ONLY_STATIC_LIBRARY)

kmpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO mohabouje/WinToast
  REF "v${VERSION}"
  SHA512 50b97beeaa49247fc836a255d68a2cc1f6124386c76786f58e6fd0605ca821df33e101d30c16bf334815e8101db0a74fcb78fd2c27025eb5c18f4817855e3519
  HEAD_REF master
)

kmpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DWINTOASTLIB_BUILD_EXAMPLES=OFF
        -DWINTOASTLIB_QT_ENABLED=OFF
)

kmpkg_cmake_build(TARGET WinToast)

if (NOT DEFINED KMPKG_BUILD_TYPE OR KMPKG_BUILD_TYPE STREQUAL "release")
  file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${KMPKG_TARGET_STATIC_LIBRARY_PREFIX}WinToast${KMPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
endif()
if (NOT DEFINED KMPKG_BUILD_TYPE OR KMPKG_BUILD_TYPE STREQUAL "debug")
  file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/${KMPKG_TARGET_STATIC_LIBRARY_PREFIX}WinToast${KMPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
endif()
file(INSTALL "${SOURCE_PATH}/include/wintoastlib.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")

configure_file("${CMAKE_CURRENT_LIST_DIR}/Config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/unofficial-${PORT}/unofficial-${PORT}-config.cmake" @ONLY)

kmpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.txt")