kmpkg_check_linkage(ONLY_STATIC_LIBRARY)

kmpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO itay-grudev/SingleApplication
    REF "v${VERSION}"
    SHA512 6d26f87e67cc8f95463d49bb2f1cd4a2132b909e8dcc302eac2f7c2623f4627c3467627098103f54b80aeaa0a56ff613406f526007d206b4391174e0c073566a
    HEAD_REF master
)

set(QAPPLICATION_CLASS QGuiApplication)
kmpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DQT_DEFAULT_MAJOR_VERSION=6
        -DQAPPLICATION_CLASS=${QAPPLICATION_CLASS}
)

kmpkg_cmake_build(TARGET SingleApplication)

if (NOT DEFINED KMPKG_BUILD_TYPE OR KMPKG_BUILD_TYPE STREQUAL "release")
  file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${KMPKG_TARGET_STATIC_LIBRARY_PREFIX}SingleApplication${KMPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
endif()
if (NOT DEFINED KMPKG_BUILD_TYPE OR KMPKG_BUILD_TYPE STREQUAL "debug")
  file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/${KMPKG_TARGET_STATIC_LIBRARY_PREFIX}SingleApplication${KMPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
endif()
file(INSTALL "${SOURCE_PATH}/singleapplication.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include")

configure_file("${CMAKE_CURRENT_LIST_DIR}/Config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/${PORT}/${PORT}-config.cmake" @ONLY)

kmpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")